target= end.o file.o main.o other.o stud_add.o stud_del.o stud_mod.o stud_show.o stud_sort.o
compile= cc
flag= c

exe:$(target)
			$(compile) -$(flag) -o exe
main.o:main.c
			$(compile) -$(flag) main.c
other.o:other.c
			$(compile) -$(flag) other.c
end.o:end.c
			$(compile) -$(flag) end.c
file.o:file.c
			$(compile) -$(flag) file.c
stud_add.o:stud_add.c 
			$(compile) -$(flag) stud_add.c
stud_del.o:stud_del.c 
			$(compile) -$(flag) stud_del.c
stud_mod.o:stud_mod.c  
			$(compile) -$(flag) stud_mod.c
stud_show.o:stud_show.c 
			$(compile) -$(flag) stud_show.c
stud_sort.o:stud_sort.c
			$(compile) -$(flag) stud_sort.c
